#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check ESLint Standards
pnpm lint:fix ||
(
        echo 'Code format checks failed'
        false; 
)
# If everything passes... Now we can commit
echo '✅ Formatting checks passed'