#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# Check ESLint & prettier Standards
pnpm lint:fix ||
(
        echo 'Linting failed'
        false;
)



# If everything passes... Now we can commit
echo '✅ ESlint, Formatting checks passed'